### ISSUE TITLE
[Bug] Metrics for "Zendesk Messaging" tickets are incorrect

### ISSUE THREAD

**Issue by elishasand** [fivetran/dbt_zendesk#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Zendesk Messaging is an alternative to Zendesk Live Chat. 

The Messaging conversation with the user is saved as a ticket and this is the only entity we have to work with when analyzing our Messaging performance (There is no designated API like with ZD Live Chat).

The problem is that the metrics calculated here by Fivetran for ZD Messaging tickets are off. 

This mostly has to do with how the Messaging data is saved in the Comments table. 
For example he logic used:  
```  
case when coalesce(ticket_comments.count_public_agent_comments, 0) = 0
    then null
    else ticket_reply_times_calendar.first_reply_time_calendar_minutes
end as first_reply_time_calendar_minutes,
```
This created many nulls for Messaging tickets since the actual replies are not logged as individual comments and so many times the `count_public_agent_comments = 0` although the agent has responded many times. 

Is there a way to fix this and address the ZD Messaging tickets metrics? 

### Expected behavior

Calculate ZD Messaging ticket metrics correctly

### dbt Project configurations

ZD Messaging metrics are calculated correctly. 

### Package versions

dbt_zendesk

### What database are you using dbt with?

snowflake

### dbt Version

1.6.6

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @elishasand thanks for opening this issue! This is actually something that has come up in the past and I believe is being actively being investigated at the connector level. Since the messaging and chat data comes in as a single comment, it is quite difficult for us to parse through this and calculate proper metrics from the data as it currently is synced. 

As such, we are planning to hold off on making any updates to the dbt package until there is an update from the connector side to properly handle chat and messaging tickets. I would recommend opening a [support ticket](https://support.fivetran.com/hc/en-us) to let our connector team know that this is something you would like to see. Once this update is applied at the connector we will then make the appropriate updates to the data model.

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Marking this as wont fix until appropriate updates are applied at the connector level.

**Comment by fivetran-joemarkiewicz** [comment]
I will close out this issue as the connector will soon support the Zendesk Messaging tickets. While this has not yet been rolled out to the connector, it should be live in the near future. Please be sure to follow Issue #137 for progress.
