### ISSUE TITLE
Integer overflow error with zendesk__ticket_backlog model on Redshift

### ISSUE THREAD

**Issue by mjirv** [fivetran/dbt_zendesk#27]
Hi all. We are trying to set up the Zendesk package but running into an error. When running the `zendesk__ticket_backlog` model, we get an Integer Overflow error message. It looks like our Zendesk user ID is a bigint, but there is logic in the package casting the field to Integer during a join.

We are on Redshift. Full error message is below:

```sql
Completed with 1 error and 0 warnings:
Database Error in model zendesk__ticket_backlog (models/zendesk__ticket_backlog.sql)
  Overflow (Integer valid range -2147483648 to 2147483647)
  DETAIL:  
    -----------------------------------------------
    error:  Overflow (Integer valid range -2147483648 to 2147483647)
    code:      1207
    context:   Value: '12415410808', Character: '8'
    query:     21488955
    location:  :0
    process:   query6_84_21488955 [pid=0]
    -----------------------------------------------
  compiled SQL at target/run/zendesk/models/zendesk__ticket_backlog.sql
```

I can fix locally by removing the `cast(... as {{ dbt_utils.type_int() }})` statements in `dbt_modules/zendesk/models/zendesk__ticket_backlog.sql` (starting on line 75), but I'm not sure if the casts in there for a reason.

Thanks in advance for your help! @annichia fyi.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mjirv, thanks for opening this issue. I was able to add the same integer value you provided in the error into my redshift data and was able to replicate the same error. 

The reason for the casting of the ids is because we noticed some id datatypes are not consistently converted to integer datatypes following the `int_zendesk__field_history_pivot` logic. In order to ensure our joins do not fail in the case where a field is not properly cast to an integer datatype, we leverage the dbt_utils.datatype macro to catch any of these possible issues. 

However, we did not foresee Zendesk creating ids that are too large for Redshifts integer datatype! To fix this, I updated the casting calls within the joins to leverage the `dbt_utils.type_bigint()` macro in order for this to work on redshift with ids that exceed the standard integer range. I tested this on my own dataset and was able to succesfully run the `zendesk__ticket_backlog` model. Would you be able to test the working branch and let us know if the error is fixed? You can use the below `packages.yml` config to test the working branch:

```yml
packages:
  - git: https://github.com/fivetran/dbt_github_source.git
    revision: redshift-int-fix
    warn-unpinned: false
```

Let me know if you have any questions!

**Comment by mjirv** [comment]
@fivetran-joemarkiewicz that worked perfectly! Thank you for taking a look at this so quickly.

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear! I just opened a PR #28 to address these changes!

**Comment by fivetran-joemarkiewicz** [comment]
@mjirv We just cut a new release of the package (`v0.4.1`) which includes this change. The release should be live later today on the dbt hub. 

Closing this issue as it has been resolved. Thanks again for opening the issue!
