### ISSUE TITLE
BUG - Touch Resolution Logic

### ISSUE THREAD

**Issue by matthew-skinner** [fivetran/dbt_zendesk#32]
**Are you a current Fivetran customer?** 

Matthew Skinner, Data Analytics Architect, Pluralsight, Inc

**Describe the bug**

When calculating "is_one_touch_resolution" and "is_two_touch_resolution" in model int_zendesk__comment_metrics the cte "final" is selecting  these two columns as count_internal_comments where it should be count_agent_comments. 

This produces an undesired count for what is considered to be one touch/two touch by including internal only comments in the count. This fix also handles erroneous multi-touch count.

**Steps to reproduce**
1. run the model as normal
2. See error in data

**Expected behavior**
see description

**Project variables configuration**
irrelevant
 
**Package Version**
version: 0.4.0

**Warehouse**
Snowflake

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [x ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @matthew-skinner 👋 thanks for opening this Issue and catching this error in the intermediate model.

After taking a look at the data I would agree with your issue description and how this is causing incorrect multi-touch metrics. It seems like this would be a relatively easy fix to this and the downstream models to capture the correct agent count for the metric. I noticed you said you would be happy to open a PR. If so, feel free to open a PR to the `bug-fix/touch-resolution` branch and we will be able to review/merge relatively quickly!

Otherwise, we will add this bug fix to our task log and I will notify you here for when we are able to assign and implement the fix.

Thanks!

**Comment by matthew-skinner** [comment]
I have the fix ready, but am getting a 403 unauthorized for the repo.

Thanks,

MS

**Comment by fivetran-joemarkiewicz** [comment]
@matthew-skinner thanks for again for contributing to our Zendesk package! I am excited to let you know that I have just cut the `v0.5.1` release of the dbt_zendesk package which includes the updates from your PR. 

The release should be live by either today or tomorrow on the [dbt hub](https://hub.getdbt.com/fivetran/zendesk/latest/). With the latest release this Issue has been addressed and I will close the ticket. Please feel free to re-open this issue or create a new issue if you have any further questions.

Thanks again! 🎉
