### ISSUE TITLE
[Feature] support for multiple zendesk connectors

### ISSUE THREAD

**Issue by mhadole-tc** [fivetran/dbt_zendesk#85]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Feature to use this package for multuple Zendesk connectors simultaneously.

This feature is already implemented in dbt-xero packages: [unioning-multiple-xero-connectors](https://github.com/fivetran/dbt_xero#unioning-multiple-xero-connectors)

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mhadole-tc thanks so much for opening this Feature Request. I think this would be a great feature enhancement.

I am curious, what is the use case in your situation for multiple Zendesk connectors?

**Comment by mhadole-tc** [comment]
We have separate Zendesk instances for every line of business but the requirement is to have all the analytics in one dashboard/place. ideally, I am looking for combined  Zendesk models with individual Zendesk instance identier in models.

**Comment by fivetran-joemarkiewicz** [comment]
@mhadole-tc that makes sense to me and I can understand why you would want to have all the Zendesk models under one hood. 

This is feature request is most likely something we will pick up in a future quarter. Our next quarterly planning initiative will likely take place after the holidays. I will be sure to post back here once we decide to pick this up and integrate into the Zendesk package!

However, if you are interested in opening a PR for the package to have this support, I would be happy to help with any questions you may have. Otherwise, we will pick this up following the holidays!

**Comment by fivetran-jamie** [comment]
hey there, looks like this got lost for a bit -- there's a duplicate ticket that is open (and soon to be worked on) [here](https://github.com/fivetran/dbt_zendesk/issues/124), so please follow along there! will close this issue to defer to the more recent one
